const API='https://pokeapi.co/api/v2';const ranges={1:[1,151],2:[152,251],3:[252,386],4:[387,493],5:[494,649],6:[650,721],7:[722,809],8:[810,905],9:[906,1025]};let current=[],gen=1,timer,seconds,score=0,names=[];
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='dex'&&!document.getElementById('grid').dataset.loaded)loadGen(1)}
const gens=document.getElementById('gens');for(let i=1;i<=9;i++){let b=document.createElement('button');b.className='tab'+(i===1?' active':'');b.textContent='Generación '+i;b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadGen(i)};gens.appendChild(b)}
async function loadGen(g){gen=g;let [a,z]=ranges[g];document.getElementById('grid').innerHTML='<p>Cargando Pokémon...</p>';try{current=await Promise.all(Array.from({length:z-a+1},(_,i)=>fetch(API+'/pokemon/'+(a+i)).then(r=>r.json())));render();document.getElementById('grid').dataset.loaded='1'}catch(e){document.getElementById('grid').innerHTML='<p>No se pudo cargar la Pokédex.</p>'}}
function render(){let q=document.getElementById('search').value.toLowerCase();document.getElementById('grid').innerHTML=current.filter(p=>p.name.includes(q)).map(p=>`<article class="card"><img loading="lazy" src="${p.sprites.other['official-artwork'].front_default||p.sprites.front_default}"><div class="num">#${String(p.id).padStart(4,'0')}</div><div class="name">${p.name}</div><div class="types">${p.types.map(t=>`<span class="type">${t.type.name}</span>`).join('')}</div></article>`).join('')||'<p>No encontrado.</p>'}document.getElementById('search').oninput=render;
async function allNames(){try{let d=await fetch(API+'/pokemon?limit=2000').then(r=>r.json());names=d.results.map(x=>x.name)}catch(e){}}allNames();
function startBasta(){let letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';document.getElementById('letter').textContent=letters[Math.floor(Math.random()*letters.length)];seconds=15;document.getElementById('time').textContent=seconds;document.getElementById('answer').disabled=false;document.getElementById('check').disabled=false;document.getElementById('answer').value='';document.getElementById('answer').focus();clearInterval(timer);timer=setInterval(()=>{document.getElementById('time').textContent=--seconds;if(seconds<=0)checkBasta()},1000)}function checkBasta(){clearInterval(timer);let ans=document.getElementById('answer').value.trim().toLowerCase(),l=document.getElementById('letter').textContent;document.getElementById('answer').disabled=true;document.getElementById('check').disabled=true;if(ans&&ans[0].toUpperCase()===l&&names.includes(ans)){score++;document.getElementById('score').textContent=score;document.getElementById('result').textContent='✅ ¡Correcto! +1 punto'}else document.getElementById('result').textContent=ans?'❌ Respuesta incorrecta':'⏰ ¡Tiempo!';}document.getElementById('start').onclick=startBasta;document.getElementById('check').onclick=checkBasta;
const c=document.getElementById('canvas'),ctx=c.getContext('2d');ctx.lineWidth=6;ctx.lineCap='round';ctx.strokeStyle='#111827';let drawing=false;c.onpointerdown=e=>{drawing=true;ctx.beginPath();let r=c.getBoundingClientRect();ctx.moveTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height)};c.onpointermove=e=>{if(!drawing)return;let r=c.getBoundingClientRect();ctx.lineTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);ctx.stroke()};c.onpointerup=()=>drawing=false;c.onpointerleave=()=>drawing=false;document.getElementById('clear').onclick=()=>ctx.clearRect(0,0,c.width,c.height);let chosen;document.getElementById('new').onclick=async()=>{let id=Math.floor(Math.random()*1025)+1;chosen=await fetch(API+'/pokemon/'+id).then(r=>r.json());document.getElementById('pokeName').textContent=chosen.name;document.getElementById('pokeImg').src=chosen.sprites.other['official-artwork'].front_default;document.getElementById('pokeImg').classList.remove('hidden');document.getElementById('hide').disabled=false;document.getElementById('reveal').disabled=false;ctx.clearRect(0,0,c.width,c.height);document.getElementById('drawResult').textContent=''};document.getElementById('hide').onclick=()=>{document.getElementById('pokeImg').classList.add('hidden');document.getElementById('drawResult').textContent='🎨 ¡Ahora dibújalo de memoria!'};document.getElementById('reveal').onclick=()=>document.getElementById('pokeImg').classList.remove('hidden');
let soundOn=true;document.getElementById('sound').onclick=()=>{soundOn=!soundOn;document.getElementById('sound').textContent=soundOn?'🔊':'🔇'};document.getElementById('lang').onclick=()=>alert('La versión bilingüe está preparada para ampliarse.');
